### ISSUE TITLE
Speeding up guildInfo 

### ISSUE THREAD

**Issue by ahnl** [Testausserveri/testausapis#4]
![image](https://user-images.githubusercontent.com/46541386/162934939-e89c57c0-0385-464a-9c0e-95c3c13b47d8.png)

The load times are currently around 1s for each request, which is bad:
- for the API user
  - the Next.js recode of the website fetches data from this endpoint server-side, which adds 1 second to the load time
- for the server
  - can overload server, this request is used in large scale and really frequently
  - can become an entry point for denial of service attack

I suggest that we implement cache for at least this endpoint. Server would have its own routine to refresh response data every few seconds, and the HTTP server would just serve response from a memory variable.

**Comment by Esinko** [comment]
I implemented a cache for the database side. I am unsure if Discord.js already caches the other data, but if you could (@ahnl) run your tests again, we can see if database caching is enough.
