### ISSUE TITLE
Inefficient guildInfo updating

### ISSUE THREAD

**Issue by ahnl** [Testausserveri/testausapis#5]
I guess it's because of getMessagesLeaderboard() function, which uses discordUtility.getUserById() function to translate user id to username. The latter function fetches 5 users (number of users displayed on the leaderboard) every 5 seconds (refresh rate) from Discord API seemingly without cache.

Needs investigating.

**Comment by ahnl** [comment]
<img width="319" alt="image" src="https://user-images.githubusercontent.com/46541386/167151052-c7bdce4e-f50f-444c-8b79-905b5c28b5af.png">

A picture of how long an update takes and here's what it consists of:
```js
    const messagesToday = await database.getMessageCount(mainServer)
    const memberCount = await discordUtility.getMemberCount(mainServer)
    const membersOnline = await discordUtility.getOnlineCount(mainServer)
    const config = await database.getDataCollectionConfig(mainServer)
    const boostStatus = await discordUtility.getBoostStatus(mainServer, config?.allowed ?? [])
    const codingLeaderboard = await getCodingLeaderboard()
    const messagesLeaderboard = await getMessagesLeaderboard()
```

**Comment by Esinko** [comment]
There should now be a cache for user date in `getUserById`. Could you run the test again?

**Comment by Chicken** [comment]
The code should probably also take advantage of parallel tasks with `Promise.all()` instead of doing these asynchronous tasks sequentially.

**Comment by Esinko** [comment]
A very good point.

**Comment by Esinko** [comment]
> The code should probably also take advantage of parallel tasks with `Promise.all()` instead of doing these asynchronous tasks sequentially.

I implemented that [here](https://github.com/Testausserveri/testausapis/commit/c63271e171372b8ef6f24a37494c5d32ee3d9cc9)

**Comment by Esinko** [comment]
Should we consider this issue closed @ahnl?
