### ISSUE TITLE
API versioning for breaking changes

### ISSUE THREAD

**Issue by developerfromjokela** [Testausserveri/testausapis#8]
At least few times API has changed, and that broke some of my info widgets.
Please do proper versioning for API

**Comment by ahnl** [comment]
What routes had been broken?

**Comment by developerfromjokela** [comment]
The API in testausserveri antiikki site showing masterminds statuses for
example. It was working before some changes happened.

**Comment by ahnl** [comment]
Haven't touched. Reminder to other contributors to be careful not to make breaking changes.
